# spring:
#   application:
#     name: project-receptar
#   datasource:
#     url: jdbc:postgresql://ep-crimson-pine-amb9pxc2.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop